import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {defaultRules, screen, evaluate, validateRules, diffResults, type Stock, type Rule} from '../lib/screener.ts';
const snapshot=JSON.parse(fs.readFileSync(new URL('../public/data/snapshot.json',import.meta.url),'utf8'));
const sample:Stock={code:'TEST',name:'测试样本（非真实数据）',industry:'测试',metrics:{pe:20,revenueGrowth:5},errors:[],sources:{},prices:[],evidencePath:''};
const rule=(field:Rule['field'],op:Rule['op'],value:number):Rule=>({id:`${field}-${op}-${value}`,field,op,value});

test('exact threshold: inclusive and exclusive operators differ',()=>{assert.equal(evaluate(sample,[rule('pe','<=',20)]).status,'included');assert.equal(evaluate(sample,[rule('pe','<',20)]).status,'excluded')});
test('missing fields are unknown, never zero',()=>assert.equal(evaluate(sample,[rule('profitGrowth','>',0)]).status,'unknown'));
test('negative PE is inapplicable, not cheap',()=>assert.equal(evaluate({...sample,metrics:{pe:-5}},[rule('pe','<',20)]).status,'unknown'));
test('AND false takes precedence over unknown, but preserves both reasons',()=>{const r=evaluate(sample,[rule('pe','<',10),rule('volatility','<',30)]);assert.equal(r.status,'excluded');assert.deepEqual(r.checks.map(c=>c.status),['fail','unknown'])});
test('contradictory bounds rejected; equal inclusive bounds allowed',()=>{assert.ok(validateRules([rule('pe','>',20),rule('pe','<=',20)]).length);assert.equal(validateRules([rule('pe','>=',20),rule('pe','<=',20)]).length,0)});
test('empty, unsupported and nonfinite rules rejected',()=>{for(const r of [[],[rule('pe','<',NaN)],[{field:'__proto__',op:'>',value:1}],[{field:'pe',op:'eval',value:1}]])assert.ok(validateRules(r).length)});
test('zero matches does not relax a valid rule',()=>{const r=screen(snapshot.stocks,[rule('marketCap','>',1e15)]);assert.equal(r.filter(s=>s.status==='included').length,0)});
test('result diffs use actual old and new rules',()=>{const before=screen([sample],[rule('pe','<',10)]),after=screen([sample],[rule('pe','<',30)]);assert.deepEqual(diffResults(before,after).added.map(s=>s.code),['TEST']);assert.deepEqual(diffResults(after,before).removed.map(s=>s.code),['TEST'])});
test('snapshot provenance and financial cutoffs verified',()=>{assert.equal(snapshot.stocks.length,50);assert.equal(new Set(snapshot.stocks.map((s:Stock)=>s.code)).size,50);for(const s of snapshot.stocks){const e=JSON.parse(fs.readFileSync(new URL('../public'+s.evidencePath,import.meta.url),'utf8'));assert.equal(e.code,s.code);assert.equal(s.tradeDate,snapshot.asOf);if(s.metrics.revenueGrowth!=null)assert.ok(s.disclosedAt<=snapshot.asOf);assert.ok(s.sources.financial.startsWith('https://datacenter-web.eastmoney.com/'));assert.ok(s.sources.prices.startsWith('https://web.ifzq.gtimg.cn/'));assert.equal(s.metrics.pe,e.records.valuation.raw.PE_TTM);assert.equal(s.metrics.revenueGrowth,e.records.financial.raw.TOI_RATIO)}});
test('recompute volatility and drawdown independently from retained observations',()=>{for(const s of snapshot.stocks){assert.equal(s.prices.length,61);assert.equal(s.prices.at(-1).date,snapshot.asOf);const returns=s.prices.slice(1).map((p:{close:number},i:number)=>p.close/s.prices[i].close-1);const mean=returns.reduce((a:number,b:number)=>a+b,0)/60;const vol=Math.sqrt(returns.reduce((sum:number,r:number)=>sum+(r-mean)**2,0)/59*252)*100;assert.ok(Math.abs(vol-s.metrics.volatility)<1e-9);let dd=0;for(let i=0;i<61;i++)for(let j=i;j<61;j++)dd=Math.max(dd,100*(1-s.prices[j].close/s.prices[i].close));assert.ok(Math.abs(dd-s.metrics.drawdown)<1e-9)}});
test('default result can be reconstructed from all rule checks',()=>{const result=screen(snapshot.stocks,defaultRules);for(const row of result){assert.equal(row.checks.length,defaultRules.length);assert.equal(row.status==='included',row.checks.every(c=>c.status==='pass'))}assert.equal(result.filter(r=>r.status==='included').length,5)});
