'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,Bookmark,Check,ChevronRight,ChevronsUpDown,Code2,Database,Download,FlaskConical,GitCompareArrows,Info,Layers3,Loader2,PanelLeftClose,Plus,Search,ShieldCheck,SlidersHorizontal,Sparkles,Trash2,X} from 'lucide-react';
import {defaultRules,fields,format,screen,validateRules,diffResults,type Rule,type Field,type Snapshot,type Stock} from '../lib/screener';

type Saved={name:string;rules:Rule[];version:string;savedAt:string};
type Interpretation={summary:string;assumptions:string[];questions:string[];unsupported:string[];mode:string};
const examples=[{label:'经营改善，估值适中',prompt:'找经营改善、估值合理、走势相对稳定的公司',rules:defaultRules},
 {label:'低估值 · 正盈利',prompt:'市盈率不超过15倍，且上半年归母净利润为正',rules:[{id:'e1',field:'pe',op:'<=',value:15},{id:'e2',field:'profit',op:'>',value:0}] as Rule[]},
 {label:'观察低波动',prompt:'近60个观测日年化波动率低于25%，区间最大回撤小于15%',rules:[{id:'v1',field:'volatility',op:'<',value:25},{id:'v2',field:'drawdown',op:'<',value:15}] as Rule[]}];
const sourceLabels:Record<string,string>={financial:'东方财富 · 财报字段',valuation:'东方财富 · 估值快照',prices:'腾讯证券 · 历史日线 → 本地计算'};
const statusNames={included:'入选',excluded:'已排除',unknown:'待验证'};
function Sparkline({stock}:{stock:Stock}){const a=stock.prices.map(p=>p.close);if(a.length<2)return <span className="muted">行情缺失</span>;const min=Math.min(...a),max=Math.max(...a),d=a.map((v,i)=>`${i/(a.length-1)*100},${29-(v-min)/(max-min||1)*26}`).join(' ');return <svg className="sparkline" viewBox="0 0 100 32" aria-label="历史价格趋势，不代表未来表现"><polyline points={d} fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>}
export default function Home(){
 const [data,setData]=useState<Snapshot|null>(null),[dataError,setDataError]=useState('');
 const [prompt,setPrompt]=useState('找经营改善、估值合理、走势相对稳定的公司');
 const [rules,setRules]=useState<Rule[]>(defaultRules),[applied,setApplied]=useState<Rule[]>(defaultRules),[previous,setPrevious]=useState<Rule[]|null>(null);
 const [interpretation,setInterpretation]=useState<Interpretation>({summary:'示例将三个模糊意图拆解成五条可检查的条件。请核对这些定义是否符合你的想法。',assumptions:['“经营改善”暂用营收、归母净利润同比增长且当期盈利表示；不等于经营质量全面改善。','“估值合理”暂用正值 PE(TTM) ≤ 25 倍表示，不代表低估或适合所有行业。','“走势稳定”暂用60日年化波动率 ≤ 30%表示；历史平稳不保证未来平稳。'],questions:[],unsupported:[],mode:'example'});
 const [busy,setBusy]=useState(false),[aiError,setAiError]=useState(''),[tab,setTab]=useState('included'),[query,setQuery]=useState('');
 const [drawer,setDrawer]=useState<Stock|null>(null),[panel,setPanel]=useState<'saved'|'data'|'compare'|null>(null),[selected,setSelected]=useState<string[]>([]),[saved,setSaved]=useState<Saved[]>([]),[toast,setToast]=useState(''),[showMeaning,setShowMeaning]=useState(false),[confirmed,setConfirmed]=useState(true);
 async function loadData(){setDataError('');try{const r=await fetch('/data/snapshot.json');if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json() as Snapshot;if(!Array.isArray(d.stocks)||!d.stocks.length)throw Error('无有效股票记录');setData(d)}catch{setDataError('数据快照加载失败。未生成筛选结果，请检查网络后重试。')}}
 useEffect(()=>{loadData();try{const x=JSON.parse(localStorage.getItem('stock-lens-strategies')||'[]');if(Array.isArray(x))setSaved(x.filter(s=>s&&typeof s.name==='string'&&validateRules(s.rules).length===0))}catch{}},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)}},[toast]);
 const errors=validateRules(rules),dirty=JSON.stringify(rules)!==JSON.stringify(applied);
 const results=useMemo(()=>data?screen(data.stocks,applied):[],[data,applied]);
 const draftCount=useMemo(()=>data&&!errors.length?screen(data.stocks,rules).filter(r=>r.status==='included').length:null,[data,rules,errors.length]);
 const diff=useMemo(()=>data&&previous?diffResults(screen(data.stocks,previous),results):null,[data,previous,results]);
 const counts={included:results.filter(r=>r.status==='included').length,excluded:results.filter(r=>r.status==='excluded').length,unknown:results.filter(r=>r.status==='unknown').length};
 const visible=results.filter(r=>(tab==='all'||r.status===tab)&&(`${r.stock.name}${r.stock.code}${r.stock.industry}`).includes(query));
 function update(id:string,patch:Partial<Rule>){setRules(v=>v.map(r=>r.id===id?{...r,...patch}:r))}
 function execute(){if(errors.length||!confirmed||interpretation.unsupported.length)return;setPrevious(applied);setApplied(rules.map(r=>({...r})));setToast('已按确认条件重新计算，结果与数据版本均可追溯。')}
 function useExample(i:number){setRules(examples[i].rules.map(r=>({...r})));setPrompt(examples[i].prompt);setInterpretation({summary:'已载入预设示例规则；这不是模型生成结果。你可以修改后执行。',assumptions:i===0?['经营改善采用营收、归母净利润同比增长且当期盈利；估值和稳定性仅使用明示阈值。']:['示例阈值用于演示筛选机制，不构成投资建议。'],questions:[],unsupported:[],mode:'example'});setConfirmed(true);setAiError('')}
 async function interpret(){setBusy(true);setAiError('');try{const r=await fetch('/api/interpret',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});const x=await r.json() as Interpretation & {rules:Rule[];error?:string};if(!r.ok)throw Error(x.error||'解析失败');setRules(x.rules);setInterpretation(x);setConfirmed(false);setShowMeaning(true)}catch(e){setAiError(e instanceof Error?e.message:'请求失败')}finally{setBusy(false)}}
 function save(){if(dirty||!data){setToast('请先执行当前条件，再保存策略。');return}const item={name:applied.map(r=>`${fields[r.field].label}${r.op}${r.value}`).join(' · ').slice(0,65),rules:applied,version:data.version,savedAt:new Date().toISOString()};const next=[item,...saved].slice(0,12);try{localStorage.setItem('stock-lens-strategies',JSON.stringify(next));setSaved(next);setToast('策略已保存到当前浏览器。')}catch{setToast('浏览器存储不可用，未保存。')}}
 function exportResults(){if(!data)return;const blob=new Blob([JSON.stringify({dataset:data.version,asOf:data.asOf,universe:data.universe,rules:applied,results:results.map(r=>({code:r.stock.code,name:r.stock.name,status:r.status,checks:r.checks,evidence:r.stock.evidencePath})),limitations:data.limitations},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='知条件-可复核筛选结果.json';a.click();URL.revokeObjectURL(a.href)}
 function toggle(code:string){setSelected(x=>x.includes(code)?x.filter(c=>c!==code):x.length<3?[...x,code]:x);if(!selected.includes(code)&&selected.length>=3)setToast('最多同时比较3家公司。')}
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="/"><span className="brand-symbol"><Layers3 size={21}/></span><span>知条件<small>STOCK LENS</small></span></a><div className="nav-label">研究工作台</div><button className={`nav-item ${panel===null?'active':''}`} onClick={()=>setPanel(null)}><SlidersHorizontal size={18}/>策略实验室<span className="nav-dot"/></button><button className={`nav-item ${panel==='saved'?'active':''}`} onClick={()=>setPanel('saved')}><Bookmark size={18}/>我的策略<span className="nav-count">{saved.length}</span></button><button className={`nav-item ${panel==='data'?'active':''}`} onClick={()=>setPanel('data')}><Database size={18}/>数据与口径</button><div className="sidebar-note"><FlaskConical size={20}/><strong>把直觉，变成条件。</strong><p>每一个筛选结果，<br/>都有可检查的理由。</p><span>RESEARCH EDITION / 01</span></div><div className="sidebar-foot"><span className="avatar">研</span><div>研究示范工作区<small>本地保存 · 无需登录</small></div></div></aside>
  <main><header className="topbar"><div className="breadcrumb">研究工作台 <ChevronRight size={13}/> <strong>{panel==='saved'?'我的策略':panel==='data'?'数据与口径':panel==='compare'?'候选比较':'策略实验室'}</strong></div><button className="snapshot-badge" onClick={()=>setPanel('data')}><span/>历史快照 {data?.asOf||'加载中'}</button></header><nav className="mobile-nav" aria-label="移动导航"><button onClick={()=>setPanel(null)}>策略实验室</button><button onClick={()=>setPanel('saved')}>我的策略 · {saved.length}</button><button onClick={()=>setPanel('data')}>数据与口径</button></nav>
   <div className="workspace"><div className="page-heading"><div><div className="eyebrow">FROM INTENT TO EVIDENCE</div><h1>{panel==='saved'?'让研究，可以继续。':panel==='data'?'每一个数字，都有出处。':panel==='compare'?'并排查看，而非替你排名。':'你的选股想法，值得说清楚。'}</h1><p>{panel==='saved'?'保存的是规则与数据版本，不是对未来收益的承诺。':panel==='data'?'了解样本范围、数据时点、计算方式与已知边界。':panel==='compare'?'相同规则、相同快照，比较候选公司的真实差异。':'从一句自然语言，到一组透明条件。理解、调整，再验证。'}</p></div><span className="edition">A 股研究工具 <ArrowUpRight size={14}/></span></div>
   {dataError?<div className="alert error">{dataError}<button onClick={loadData}>重新加载</button></div>:!data?<div className="loading"><Loader2 className="spin"/>正在载入真实数据快照…</div>:panel==='saved'?<section className="saved-grid">{saved.length?saved.map((s,i)=><article className="card saved-card" key={i}><Bookmark size={22}/><h3>{s.name}</h3><p>{s.rules.length} 条条件 · {s.version}</p><small>{new Date(s.savedAt).toLocaleString('zh-CN')}</small><button className="primary" onClick={()=>{setRules(s.rules);setPrompt(s.name);setInterpretation({summary:'已载入保存的规则。当前执行会使用本页面数据版本，请核对后确认。',assumptions:[`保存时数据版本：${s.version}`],questions:[],unsupported:[],mode:'saved'});setConfirmed(true);setPanel(null)}}>载入并检查 <ArrowRight size={15}/></button></article>):<div className="empty card"><Bookmark/><h3>还没有保存的策略</h3><p>完成一次筛选后，点击「保存策略」，下次从这里继续。</p><button onClick={()=>setPanel(null)}>前往策略实验室</button></div>}</section>:panel==='data'?<section className="card data-page"><div className="section-title"><Database/><h2>数据档案</h2><span className="tag">{data.version}</span></div><div className="data-grid"><div><small>样本范围</small><strong>{data.stocks.length} 只手工选取的 A 股</strong><p>跨行业研究示范样本，不是指数成分，也不是全市场或推荐名单。</p></div><div><small>财务期次</small><strong>2026 年半年度累计</strong><p>比较上年同期。不是单季度增长率，不使用未来披露记录。</p></div><div><small>估值与行情基准</small><strong>{data.asOf}</strong><p>固定历史快照，不提供实时价格或历史时点回测。</p></div><div><small>抓取时间</small><strong>{new Date(data.fetchedAt).toLocaleString('zh-CN')}</strong><p>来源：{data.source}。指标保留原始记录。</p></div></div><h3>口径字典</h3><div className="dictionary">{Object.entries(fields).map(([k,f])=><div key={k}><strong>{f.label}<code>{f.raw}</code></strong><p>{f.definition}</p></div>)}</div><h3>已知边界</h3>{data.limitations.map(x=><p className="boundary" key={x}><Info size={15}/>{x}</p>)}<div className="alert">未接入扶摇／iFinD。当前使用公开替代数据；没有把 API 缺失伪装成已接入。</div><a className="text-link" href="/data/snapshot.json" target="_blank" rel="noreferrer">查看完整数据快照 <ArrowUpRight size={14}/></a></section>:panel==='compare'?<section className="card compare-page"><button className="text-link" onClick={()=>setPanel(null)}>← 返回筛选结果</button>{selected.length?<div className="table-scroll"><table><thead><tr><th>指标 / 原始值</th>{selected.map(c=>{const s=data.stocks.find(s=>s.code===c)!;return <th key={c}>{s.name}<small>{c} · {s.industry}</small></th>})}</tr></thead><tbody>{Object.entries(fields).map(([k,f])=><tr key={k}><td>{f.label}（{f.unit}）</td>{selected.map(c=><td key={c}>{format(data.stocks.find(s=>s.code===c)!.metrics[k as Field],k as Field)}</td>)}</tr>)}</tbody></table></div>:<div className="empty"><p>请先在结果表格选择最多3家公司。</p></div>}</section>:<>
   <section className="intent-card"><div className="intent-title"><span className="icon-square"><Sparkles size={18}/></span><div><h2>你想寻找什么样的公司？</h2><p>描述关注点，AI 提出规则；确认含义后，由数据执行。</p></div><span className="tag subtle">01 / 理解意图</span></div><div className="prompt-row"><textarea aria-label="选股意图" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={800} rows={2}/><button className="primary" disabled={busy||!prompt.trim()} onClick={interpret}>{busy?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'正在解析':'解析我的想法'}{!busy&&<ArrowRight size={16}/>}</button></div><div className="example-row"><span>试试示例</span>{examples.map((e,i)=><button key={e.label} onClick={()=>useExample(i)}>{e.label}<ArrowUpRight size={12}/></button>)}<span className="example-disclosure">示例为预设规则，非实时 AI 输出</span></div>{aiError&&<div className="alert error" role="alert">{aiError}</div>}</section>
   <div className="analysis-layout"><section className="rules-panel card"><div className="section-title"><span className="step">02</span><h2>确认筛选条件</h2><span className="tag">全部满足 AND</span></div><button className="meaning-toggle" onClick={()=>setShowMeaning(!showMeaning)}><Info size={15}/>{interpretation.mode==='model'?'AI 提出的定义，需要你确认':'当前使用示例 / 手动条件'}<ChevronRight size={15} className={showMeaning?'rotate':''}/></button>{showMeaning&&<div className="meaning"><p>{interpretation.summary}</p>{[...interpretation.assumptions,...interpretation.questions].map((s,i)=><p key={i}>· {s}</p>)}{interpretation.unsupported.map((s,i)=><p className="negative" key={i}>暂不支持：{s}</p>)}{interpretation.mode==='model'&&<label className="confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已检查定义和澄清问题，确认采用这些条件</label>}</div>}
    <div className="rules-list">{rules.map((r,i)=><div className="rule" key={r.id}><div className="rule-label"><span>{String(i+1).padStart(2,'0')}</span><select aria-label={`条件${i+1}指标`} value={r.field} onChange={e=>update(r.id,{field:e.target.value as Field})}>{Object.entries(fields).map(([k,f])=><option key={k} value={k}>{f.label}</option>)}</select><button aria-label={`删除条件${i+1}`} title="删除条件" onClick={()=>setRules(v=>v.filter(x=>x.id!==r.id))}><X size={14}/></button></div><div className="rule-input"><select aria-label={`条件${i+1}运算符`} value={r.op} onChange={e=>update(r.id,{op:e.target.value as Rule['op']})}><option value=">">大于 &gt;</option><option value=">=">不低于 ≥</option><option value="<">小于 &lt;</option><option value="<=">不超过 ≤</option></select><input aria-label={`条件${i+1}阈值`} type="number" step="any" value={Number.isNaN(r.value)?'':r.value} onChange={e=>update(r.id,{value:e.target.value===''?NaN:Number(e.target.value)})}/><span>{fields[r.field].unit}</span></div><button className="rule-source" onClick={()=>setPanel('data')} title="查看数据来源与指标计算口径"><Database size={10}/>{sourceLabels[fields[r.field].source]}<ArrowUpRight size={10}/></button><p>{r.field==='pe'?'仅对正值 PE 判定；非正值标记待验证':r.field==='profitGrowth'||r.field==='revenueGrowth'?'2026 H1 累计 · 对比上年同期':r.field==='volatility'||r.field==='drawdown'?'前复权 · 最近 60 个观测日收益率':r.field==='profit'?'2026 H1 累计 · 人民币元':'基准日 2026-09-30'}</p></div>)}</div>
    <button className="add-rule" disabled={rules.length>=12} onClick={()=>setRules(v=>[...v,{id:crypto.randomUUID(),field:'marketCap',op:'>',value:100}])}><Plus size={15}/>添加条件</button>{errors.map(e=><div className="alert error" key={e}>{e}</div>)}<div className="rule-footer"><div><span>{dirty?'修改后预计入选':'当前入选'}</span><strong>{draftCount??'—'} <small>/ {data.stocks.length}</small></strong></div><button className="primary" disabled={!!errors.length||!confirmed||!!interpretation.unsupported.length} onClick={execute}>确认并筛选 <ArrowRight size={16}/></button><p>AI 解释意图 · 代码计算结果 · 数据提供依据</p></div></section>
   <section className="results-panel"><div className="source-strip"><Database size={15}/><div><strong>本次筛选的数据依据</strong><p>财务、估值：东方财富 · 行情：腾讯证券 · 波动与回撤：代码计算</p><span>行情 {data.asOf} · 财务 {data.financialPeriod} · {data.stocks.length} 只固定样本</span></div><button onClick={()=>setPanel('data')}>查看来源与口径 <ArrowUpRight size={13}/></button></div><div className="results-heading"><div><span className="step">03</span><h2>让数据回答</h2></div><div><button className="icon-button" aria-label="导出可复核结果" title="导出可复核结果" onClick={exportResults}><Download size={17}/></button><button className="secondary" onClick={save}><Bookmark size={15}/>保存策略</button></div></div><div className="metrics"><div className="metric positive"><span>满足全部条件</span><strong>{counts.included}<small>只</small></strong><p>符合已确认的筛选规则</p></div><div className="metric"><span>不符合条件</span><strong>{counts.excluded}<small>只</small></strong><p>每项排除均可查看原因</p></div><div className="metric"><span>待验证</span><strong>{counts.unknown}<small>只</small></strong><p>缺失或口径不适用</p></div></div>
    {dirty&&<div className="alert pending"><SlidersHorizontal size={16}/>条件已修改。表格仍为上次执行结果，点击「确认并筛选」更新。</div>}
    {diff&&<div className="diff-strip"><GitCompareArrows size={17}/><div><strong>与上次执行相比</strong><span>新增 {diff.added.length} 只 · 移除 {diff.removed.length} 只</span></div><p>{diff.added.length?`新增：${diff.added.map(s=>s.name).join('、')}`:''}{diff.added.length&&diff.removed.length?'；':''}{diff.removed.length?`移除：${diff.removed.map(s=>s.name).join('、')}`:''}{!diff.added.length&&!diff.removed.length?'条件调整未改变入选名单。':''}</p></div>}
    <div className="results-table card"><div className="table-toolbar"><div className="tabs">{(['included','excluded','unknown','all'] as const).map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t==='all'?'全部':statusNames[t]}<span>{t==='all'?results.length:counts[t]}</span></button>)}</div><div className="search"><Search size={14}/><input aria-label="搜索股票" placeholder="名称 / 代码" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="table-scroll"><table><thead><tr><th className="check-col"/><th>公司 / 行业</th><th>PE(TTM)</th><th>营收同比</th><th>60日走势</th><th>规则检查</th><th/></tr></thead><tbody>{visible.map(r=><tr key={r.stock.code}><td><input type="checkbox" aria-label={`比较${r.stock.name}`} checked={selected.includes(r.stock.code)} onChange={()=>toggle(r.stock.code)}/></td><td><button className="stock-name" onClick={()=>setDrawer(r.stock)}>{r.stock.name}</button><small>{r.stock.code} · {r.stock.industry}</small></td><td className="mono">{format(r.stock.metrics.pe,'pe')}<small>倍{r.stock.metrics.pe!=null&&r.stock.metrics.pe<=0?' · 不适用':''}</small></td><td className="mono">{format(r.stock.metrics.revenueGrowth,'revenueGrowth')}<small>% · 2026 H1</small></td><td><Sparkline stock={r.stock}/></td><td><button className={`status ${r.status}`} onClick={()=>setDrawer(r.stock)}>{r.status==='included'?<Check size={12}/>:<Info size={12}/>} {r.status==='included'?`${r.checks.length} / ${r.checks.length} 满足`:r.status==='excluded'?`${r.checks.filter(c=>c.status==='fail').length} 项不符`:'数据待验证'}</button></td><td><button className="arrow-button" aria-label={`查看${r.stock.name}证据`} onClick={()=>setDrawer(r.stock)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table>{!visible.length&&<div className="empty"><Search size={25}/><h3>{query?'没有匹配的公司':tab==='included'?'当前没有股票满足全部条件':'此分类暂无结果'}</h3><p>{tab==='included'?'可查看排除原因，再选择是否调整条件。不会自动放宽规则。':'可切换分类或清空搜索查看其他样本。'}</p>{tab==='included'&&<button onClick={()=>setTab('excluded')}>查看排除原因</button>}</div>}</div><div className="table-footer"><span>手工选取 {data.stocks.length} 只样本 · 按样本顺序，非投资排名</span><span>点击公司查看证据 <ArrowRight size={12}/></span></div></div>
    {selected.length>0&&<div className="compare-bar"><span>已选 {selected.length} / 3 家公司</span><button onClick={()=>setPanel('compare')}><GitCompareArrows size={15}/>并排比较 <ArrowRight size={15}/></button><button aria-label="清空比较" onClick={()=>setSelected([])}><X size={15}/></button></div>}
    <div className="research-note"><ShieldCheck size={20}/><div><strong>筛选是研究的起点，不是投资结论。</strong><p>满足条件只代表符合当前规则，不意味着低估、优质或未来上涨。所有结果基于固定历史快照。</p></div><button onClick={()=>setPanel('data')}>数据说明 <ArrowUpRight size={14}/></button></div>
   </section></div></>}
   <footer className="footer"><span>知条件 · 让每个判断都有来由</span><span>真实数据 / 确定性筛选 / 可追溯证据</span></footer></div>
  </main>
  {drawer&&<div className="overlay" onClick={()=>setDrawer(null)}><section className="drawer" role="dialog" aria-modal="true" aria-label={`${drawer.name}筛选证据`} onClick={e=>e.stopPropagation()}><div className="drawer-top"><span className="eyebrow">EVIDENCE INSPECTOR</span><button aria-label="关闭证据" onClick={()=>setDrawer(null)}><X/></button></div><h2>{drawer.name}<span>{drawer.code}</span></h2><p className="muted">{drawer.industry} · 财务 {drawer.reportDate||'缺失'} · 估值 {drawer.tradeDate||'缺失'}</p><div className="drawer-summary"><ShieldCheck size={20}/><div><strong>逐条件核验</strong><p>以下为确定性比较结果；数值不由语言模型生成。</p></div></div>{results.find(r=>r.stock.code===drawer.code)?.checks.map((c,i)=><article className="evidence-card" key={c.rule.id}><div><strong>{i+1}. {fields[c.rule.field].label}</strong><span className={`status ${c.status==='pass'?'included':c.status==='fail'?'excluded':'unknown'}`}>{c.status==='pass'?'满足':c.status==='fail'?'不满足':'待验证'}</span></div><div className="evidence-numbers"><span><small>实际值</small><b>{format(c.actual,c.rule.field)}</b> {fields[c.rule.field].unit}</span><span><small>筛选条件</small><b>{c.rule.op} {c.rule.value}</b> {fields[c.rule.field].unit}</span></div><p>{c.reason}</p><div className="evidence-provider"><Database size={12}/>{sourceLabels[fields[c.rule.field].source]}</div><div className="definition">{fields[c.rule.field].definition}</div><code>{fields[c.rule.field].raw}</code><div className="evidence-links"><a href={drawer.evidencePath} target="_blank" rel="noreferrer">查看留存原始记录 <ArrowUpRight size={12}/></a>{drawer.sources[fields[c.rule.field].source]&&<a href={drawer.sources[fields[c.rule.field].source]} target="_blank" rel="noreferrer">来源接口 <ArrowUpRight size={12}/></a>}</div></article>)}{drawer.errors.map(e=><div className="alert error" key={e}>{e}</div>)}<div className="alert">财务披露：{drawer.disclosedAt||'未知'}。抓取：{data?.fetchedAt}。增长率采用来源字段，不将缺失值视为0。</div><a className="text-link" href={`https://www.cninfo.com.cn/new/fulltextSearch?keyWord=${drawer.code}`} target="_blank" rel="noreferrer">到巨潮资讯继续核验公司披露 <ArrowUpRight size={14}/></a></section></div>}
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
 </div>
}
