'use client';
import {useState} from 'react';
import UiSelect from './UiSelect';
import {X,Plus} from 'lucide-react';
import {fields,rule,type Rule,type Field,type Group} from '../lib/screener';
export default function RuleEditor({group,rules,onChange,pending,disabled=false}:{group:Group;rules:Rule[];disabled?:boolean;onChange:(rules:Rule[])=>void;pending:(key:string)=>string|undefined}){
 const [adding,setAdding]=useState(false),[search,setSearch]=useState('');
 const grouped=[...new Set(rules.map(r=>r.field))];
 const update=(id:string,patch:Partial<Rule>)=>onChange(rules.map(r=>r.id===id?{...r,...patch}:r));
 const categories=[...new Set(Object.values(fields).filter(f=>f.group===group).map(f=>f.category))];
 return <><div className="rule-list">{grouped.map(field=>{const f=fields[field],bounds=rules.filter(r=>r.field===field);return <div className="rule" key={field}><div className="row"><div><small>{f.category}</small><h3>{f.label}</h3></div><button className="icon" aria-label={`删除${f.label}`} onClick={()=>onChange(rules.filter(r=>r.field!==field))}><X size={16}/></button></div>{bounds.map((r,i)=><div className="rule-values" key={r.id}><UiSelect label={`${f.label}边界${i+1}`} disabled={disabled} value={r.op} onValueChange={value=>update(r.id,{op:value as Rule['op']})} options={[{value:'>',label:'大于 >'},{value:'>=',label:'不低于 ≥'},{value:'<',label:'小于 <'},{value:'<=',label:'不超过 ≤'}]}/><input aria-label={`${f.label}数值${i+1}`} type="number" step="any" value={Number.isNaN(r.value)?'':r.value} onChange={e=>update(r.id,{value:e.target.value===''?NaN:Number(e.target.value)})}/><span>{f.unit}</span>{bounds.length>1&&<button className="bound-delete" aria-label={`移除${f.label}边界${i+1}`} onClick={()=>onChange(rules.filter(x=>x.id!==r.id))}>移除</button>}</div>)}<details><summary>定义与公式{pending(field)?' · 本批次数据不足':''}</summary><p>{f.definition}</p><code>{f.raw}</code>{pending(field)&&<p className="warning">{pending(field)}</p>}{bounds.length===1&&rules.length<24&&<button onClick={()=>onChange([...rules,rule(field,bounds[0].op.startsWith('>')?'<=':'>=',bounds[0].value)])}>增加另一侧边界</button>}</details></div>})}</div><button className="add" disabled={rules.length>=24} onClick={()=>setAdding(!adding)}><Plus size={15}/>{adding?'收起指标库':'添加筛选指标'}</button>{adding&&<div className="metric-picker"><input aria-label="搜索筛选指标" placeholder="搜索指标或用途，如量能、MA5" value={search} onChange={e=>setSearch(e.target.value)}/>{categories.map(c=>{const options=Object.entries(fields).filter(([k,f])=>f.group===group&&f.category===c&&!grouped.includes(k as Field)&&`${f.label}${f.category}${k}`.toLowerCase().includes(search.toLowerCase()));return !!options.length&&<div key={c}><strong>{c}</strong>{options.map(([k,f])=><button key={k} disabled={!!pending(k)} onClick={()=>{onChange([...rules,rule(k as Field,'>=',0)]);setAdding(false);setSearch('')}}>{f.label}{pending(k)&&<small>{pending(k)}</small>}</button>)}</div>})}</div>}</>;
}
